name: Oracle Siebel CRM
description: |
  Oracle Siebel CRM applications stack
version: v0.1.0
category: siebel
maintainer: Alexaner Shepel
license: # The license
projectURL: # A URL related to the catalog entry