siebel-db:
  image: 192.168.99.1:5000/oracle-12c1:clonedb
  volumes:
  - oracle-backup:/oracle/backup
  # - /oracle/conf
  volume_driver: convoy-nfs
siebel-gateway:
  environment:
    COMMAND: rungateway
    SIEBEL_CONF: /siebel/conf
  image: 192.168.99.1:5000/siebel-gateway
  links:
  - siebel-server:siebel-server
  - siebel-db:siebel-db
  volumes:
  - siebel:/siebel/conf
  volume_driver: convoy-nfs
siebel-server:
  environment:
    COMMAND: runserver
    SIEBEL_CONF: /siebel/conf
    SERVER_NAME: srvr
  image: 192.168.99.1:5000/siebel-server
  links:
  - siebel-gateway:siebel-gateway
  - siebel-db:siebel-db
  volumes:
  - siebel:/siebel/conf
  volume_driver: convoy-nfs
siebel-web:
  environment:
    COMMAND: runwebserver
    SIEBEL_CONF: /siebel/conf
  image: 192.168.99.1:5000/siebel-web
  links:
  - siebel-gateway:siebel-gateway
  - siebel-server:siebel-server
  - siebel-db:siebel-db
  volumes:
  - siebel:/siebel/conf
  volume_driver: convoy-nfs
