.catalog:
  name: "Oracle Siebel CRM"
  version: "v0.1"
  description: "Oracle Siebel CRM applications stack"
  questions:
  - variable: "SIEBEL_VERSION"
    description: "Siebel Version"
    label: "Siebel Version"
    required: true
    type: "enum"
    options:
      - "15.7"

siebel-db:
  scale: 1
siebel-gateway:
  scale: 1
siebel-server:
  scale: 1
siebel-web:
  scale: 1