.catalog:
  name: "Oracle Siebel CRM"
  version: "v0.1"
  description: "Oracle Siebel CRM applications stack"
  questions:
  - variable: "SIEBEL_VERSION"
    description: "Siebel Version"
    label: "Siebel Version"
    required: true
    type: "enum"
    options:
      - "15.7"

siebel-db:
  scale: 1
  health_check:
    port: 1521
    interval: 2000
    initializing_timeout: 600000
    unhealthy_threshold: 3
    strategy: none
    healthy_threshold: 2
    response_timeout: 2000
siebel-gateway:
  scale: 1
  health_check:
    port: 2320
    interval: 2000
    initializing_timeout: 600000
    unhealthy_threshold: 3
    strategy: none
    healthy_threshold: 2
    response_timeout: 2000
siebel-server:
  scale: 1
  health_check:
    port: 2321
    interval: 2000
    initializing_timeout: 600000
    unhealthy_threshold: 3
    strategy: none
    healthy_threshold: 2
    response_timeout: 2000
siebel-web:
  scale: 1
  health_check:
    port: 80
    interval: 2000
    initializing_timeout: 600000
    unhealthy_threshold: 3
    strategy: none
    request_line: GET "/fins_enu" "HTTP/1.0"
    healthy_threshold: 2
    response_timeout: 2000