.catalog:
  name: "Convoy NFS"
  version: "v0.1"
  description: "Convoy NFS - Docker volume plugin"
  questions:
  - variable: "NFS_SERVER"
    description: "IP or hostname of the NFS Server"
    label: "NFS Server"
    required: true
    type: "string"
  - variable: "MOUNT_DIR"
    label: "Mount Directory"
    description: "The directory on the NFS server to mount"
    type: "string"
    required: true
  - variable: "MOUNT_OPTS"
    label: "Mount Options"
    description: "Comma delimited list of mount options, for example: 'nfsvers=4,proto=udp'"
    type: "string"

siebel-db:
  scale: 1
siebel-gateway:
  scale: 1
siebel-server:
  scale: 1
siebel-web:
  scale: 1